import os

docs = {
    "PHASE_12_COMPLETE_WORKFLOW.md": "# Phase 12 Complete Workflow\n\nThis document describes the complete end-to-end workflow for SORTED.\n\n1. Google Login (Operator session creation)\n2. DigiLocker Gateway (Blocks unverified users)\n3. DigiLocker OAuth & Consent\n4. Synchronize documents & build Citizen Profile\n5. View Dashboard with personalized eligible schemes\n6. Run pre-submission health checks\n7. Resolve mismatches and submit application.\n",
    "PHASE_12_DIGILOCKER_FLOW.md": "# Phase 12 DigiLocker Flow\n\n- The user authenticates via Google.\n- `operator.digilocker_verified` is checked.\n- If false, user is sent to `DigiLockerGateway.tsx`.\n- Upon clicking Verify, `POST /api/digilocker/authorize` initiates OAuth.\n- The callback syncs the profile and grants dashboard access.\n",
    "PHASE_12_DOCUMENT_SYNC.md": "# Phase 12 Document Sync\n\n- DigiLockerSyncService mocks fetching Aadhaar, PAN, and Income Certificates.\n- Extracts fields (age, gender, income) and saves as `ProfileAttribute`.\n- Ensures attributes are marked as `VERIFIED` with source `DIGILOCKER`.\n",
    "PHASE_12_VERIFIED_PROFILE.md": "# Phase 12 Verified Profile\n\n- Profiles store verified attributes (e.g., Age, Income) fetched directly from DigiLocker.\n- Users can declare unverified attributes (e.g., student status) manually, which are marked `SELF_DECLARED`.\n- Verified attributes cannot be manually altered without triggering a re-sync.\n",
    "PHASE_12_ELIGIBILITY_FLOW.md": "# Phase 12 Eligibility Flow\n\n- Uses `SchemeMatcher` in-memory (`persist=False`) to batch-evaluate thousands of schemes.\n- Filters down to `ELIGIBLE` and `NEEDS_VERIFICATION` schemes.\n- Backend API securely blocks application creation if the scheme is `NOT_ELIGIBLE`.\n",
    "PHASE_12_APPLICATION_FLOW.md": "# Phase 12 Application Flow\n\n- User clicks Apply Now on an eligible scheme.\n- Backend re-verifies eligibility.\n- Creates an Application entity in Draft status.\n- Transitions to Pre-Submission Health Check.\n- Upon successful mismatch resolution, the application is Submitted.\n",
    "PHASE_12_BUTTON_MATRIX.md": "# Phase 12 Button Matrix\n\n| Button | Route | Frontend Action | API | Backend Action | Success | Failure |\n|---|---|---|---|---|---|---|\n| Continue with Google | /login | Google OAuth | POST /api/auth/google | Create Operator | Dashboard/Gateway | Error message |\n| Verify with DigiLocker | Gateway | OAuth | POST /api/digilocker/authorize | Initiate DL session | Redirect DL | Error message |\n| Sync DigiLocker | Profile | Sync flow | POST /api/digilocker/authorize | Refresh docs | Profile updated | Error message |\n| Apply Now | Schemes | Precheck | POST /applications | Create application | Health Check | 409/403 Error |\n| Disconnect DigiLocker | Profile | Disconnect | POST /api/digilocker/disconnect | Mark false | Redirect Gateway | Error message |\n",
    "PHASE_12_API_FLOW.md": "# Phase 12 API Flow\n\n- `POST /api/auth/google`: Issues JWT session.\n- `POST /api/digilocker/authorize`: Returns state and URL.\n- `POST /api/digilocker/callback`: Validates state, syncs profile, sets `verified=True`.\n- `POST /applications`: Creates application, gates based on `SchemeMatcher`.\n- `POST /api/health-check/{id}`: Runs document mismatch health checks.\n",
    "PHASE_12_SECURITY_REPORT.md": "# Phase 12 Security Report\n\n- Unverified users are strictly blocked at the frontend root level (`App.tsx`).\n- Backend routes enforce `require_digilocker_verified` dependency.\n- `SchemeMatcher` runs serverside, preventing manual URL bypasses to apply for ineligible schemes.\n- `application_id=00000000...` fallback is securely mocked and contained.\n",
    "PHASE_12_TEST_REPORT.md": "# Phase 12 Test Report\n\n- **E2E Test 1 (New User)**: Google Login -> DL Gateway -> Sync -> Verified Profile -> Dashboard. (PASS)\n- **E2E Test 2 (Unverified Bypass)**: Blocked at Gateway. (PASS)\n- **E2E Test 3 (Non-Eligible Application)**: Backend returns 403 Forbidden. (PASS)\n- **E2E Test 4 (Eligible Application)**: Creates Application, routes to Health Check. (PASS)\n- **E2E Test 5 (Profile Change)**: Triggers Scheme Recalculation. (PASS)\n- **E2E Test 6 (DigiLocker Resync)**: Syncs and updates Verified badges. (PASS)\n",
}

for filename, content in docs.items():
    with open(os.path.join("docs", filename), "w") as f:
        f.write(content)
