"""Add Operator table

Revision ID: 29c0d5fbb1d1
Revises: c84614b81c04
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '29c0d5fbb1d1'
down_revision: Union[str, None] = 'c84614b81c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operators',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('picture_url', sa.String(length=500), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.String(length=32), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_operators_created_at'), 'operators', ['created_at'], unique=False)
    op.create_index(op.f('ix_operators_email'), 'operators', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operators_email'), table_name='operators')
    op.drop_index(op.f('ix_operators_created_at'), table_name='operators')
    op.drop_table('operators')
    # ### end Alembic commands ###
