"""Add MyScheme missing fields

Revision ID: d823ffb8f8ad
Revises: 0007_payment_diag
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd823ffb8f8ad'
down_revision: Union[str, None] = '0007_payment_diag'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_actions_created_at'), 'actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_activities_created_at'), 'agent_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_application_events_created_at'), 'application_events', ['created_at'], unique=False)
    op.drop_constraint('applications_application_number_key', 'applications', type_='unique')
    op.drop_index('ix_applications_application_number', table_name='applications')
    op.create_index(op.f('ix_applications_application_number'), 'applications', ['application_number'], unique=True)
    op.create_index(op.f('ix_applications_created_at'), 'applications', ['created_at'], unique=False)
    op.create_index(op.f('ix_citizens_created_at'), 'citizens', ['created_at'], unique=False)
    op.create_index(op.f('ix_diagnoses_created_at'), 'diagnoses', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_health_checks_created_at'), 'health_checks', ['created_at'], unique=False)
    op.create_index(op.f('ix_mismatches_created_at'), 'mismatches', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_cases_created_at'), 'payment_cases', ['created_at'], unique=False)
    op.add_column('schemes', sa.Column('application_mode', sa.String(length=100), nullable=True))
    op.add_column('schemes', sa.Column('eligibility_general', sa.Text(), nullable=True))
    op.add_column('schemes', sa.Column('exclusions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('schemes', sa.Column('faqs', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint('schemes_scheme_code_key', 'schemes', type_='unique')
    op.drop_index('ix_schemes_scheme_code', table_name='schemes')
    op.create_index(op.f('ix_schemes_scheme_code'), 'schemes', ['scheme_code'], unique=True)
    op.create_index(op.f('ix_schemes_application_mode'), 'schemes', ['application_mode'], unique=False)
    op.create_index(op.f('ix_schemes_created_at'), 'schemes', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schemes_created_at'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_application_mode'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_scheme_code'), table_name='schemes')
    op.create_index('ix_schemes_scheme_code', 'schemes', ['scheme_code'], unique=False)
    op.create_unique_constraint('schemes_scheme_code_key', 'schemes', ['scheme_code'], postgresql_nulls_not_distinct=False)
    op.drop_column('schemes', 'faqs')
    op.drop_column('schemes', 'exclusions')
    op.drop_column('schemes', 'eligibility_general')
    op.drop_column('schemes', 'application_mode')
    op.drop_index(op.f('ix_payment_cases_created_at'), table_name='payment_cases')
    op.drop_index(op.f('ix_mismatches_created_at'), table_name='mismatches')
    op.drop_index(op.f('ix_health_checks_created_at'), table_name='health_checks')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_index(op.f('ix_diagnoses_created_at'), table_name='diagnoses')
    op.drop_index(op.f('ix_citizens_created_at'), table_name='citizens')
    op.drop_index(op.f('ix_applications_created_at'), table_name='applications')
    op.drop_index(op.f('ix_applications_application_number'), table_name='applications')
    op.create_index('ix_applications_application_number', 'applications', ['application_number'], unique=False)
    op.create_unique_constraint('applications_application_number_key', 'applications', ['application_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_application_events_created_at'), table_name='application_events')
    op.drop_index(op.f('ix_agent_activities_created_at'), table_name='agent_activities')
    op.drop_index(op.f('ix_actions_created_at'), table_name='actions')
    # ### end Alembic commands ###
