"""Phase 12 models

Revision ID: f386594ccc33
Revises: c84614b81c04
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f386594ccc33'
down_revision: Union[str, None] = 'c84614b81c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digilocker_sessions',
    sa.Column('citizen_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state')
    )
    op.create_index(op.f('ix_digilocker_sessions_citizen_id'), 'digilocker_sessions', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_digilocker_sessions_created_at'), 'digilocker_sessions', ['created_at'], unique=False)
    op.create_table('profile_attributes',
    sa.Column('citizen_id', sa.UUID(), nullable=False),
    sa.Column('attribute_name', sa.String(length=100), nullable=False),
    sa.Column('attribute_value', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_attributes_citizen_id'), 'profile_attributes', ['citizen_id'], unique=False)
    op.create_index('ix_profile_attributes_citizen_name', 'profile_attributes', ['citizen_id', 'attribute_name'], unique=True)
    op.create_index(op.f('ix_profile_attributes_created_at'), 'profile_attributes', ['created_at'], unique=False)
    op.create_table('scheme_eligibility_results',
    sa.Column('citizen_id', sa.UUID(), nullable=False),
    sa.Column('scheme_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('match_score', sa.String(length=50), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missing_information', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('profile_version', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_eligibility_citizen_scheme', 'scheme_eligibility_results', ['citizen_id', 'scheme_id'], unique=True)
    op.create_index(op.f('ix_scheme_eligibility_results_citizen_id'), 'scheme_eligibility_results', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_scheme_eligibility_results_created_at'), 'scheme_eligibility_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_scheme_eligibility_results_scheme_id'), 'scheme_eligibility_results', ['scheme_id'], unique=False)
    op.create_table('document_verifications',
    sa.Column('citizen_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('verified_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provider_reference', sa.String(length=200), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_verifications_citizen_id'), 'document_verifications', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_document_verifications_created_at'), 'document_verifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_verifications_document_id'), 'document_verifications', ['document_id'], unique=False)
    # Alter citizens columns only if they already exist (safe for fresh local DBs)
    conn = op.get_bind()
    has_is_verified = conn.execute(sa.text(
        "SELECT 1 FROM information_schema.columns "
        "WHERE table_name='citizens' AND column_name='is_verified'"
    )).fetchone()
    if has_is_verified:
        op.alter_column('citizens', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    has_constraint = conn.execute(sa.text(
        "SELECT 1 FROM information_schema.table_constraints "
        "WHERE constraint_name='citizens_digilocker_id_key' AND table_name='citizens'"
    )).fetchone()
    if has_constraint:
        op.drop_constraint('citizens_digilocker_id_key', 'citizens', type_='unique')

    has_digilocker_id = conn.execute(sa.text(
        "SELECT 1 FROM information_schema.columns "
        "WHERE table_name='citizens' AND column_name='digilocker_id'"
    )).fetchone()
    if has_digilocker_id:
        # Only create index if it doesn't already exist
        has_idx = conn.execute(sa.text(
            "SELECT 1 FROM pg_indexes WHERE tablename='citizens' AND indexname='ix_citizens_digilocker_id'"
        )).fetchone()
        if not has_idx:
            op.create_index(op.f('ix_citizens_digilocker_id'), 'citizens', ['digilocker_id'], unique=True)

    has_operator_id = conn.execute(sa.text(
        "SELECT 1 FROM information_schema.columns "
        "WHERE table_name='citizens' AND column_name='operator_id'"
    )).fetchone()
    if has_operator_id:
        has_idx2 = conn.execute(sa.text(
            "SELECT 1 FROM pg_indexes WHERE tablename='citizens' AND indexname='ix_citizens_operator_id'"
        )).fetchone()
        if not has_idx2:
            op.create_index(op.f('ix_citizens_operator_id'), 'citizens', ['operator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citizens_operator_id'), table_name='citizens')
    op.drop_index(op.f('ix_citizens_digilocker_id'), table_name='citizens')
    op.create_unique_constraint('citizens_digilocker_id_key', 'citizens', ['digilocker_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('citizens', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_document_verifications_document_id'), table_name='document_verifications')
    op.drop_index(op.f('ix_document_verifications_created_at'), table_name='document_verifications')
    op.drop_index(op.f('ix_document_verifications_citizen_id'), table_name='document_verifications')
    op.drop_table('document_verifications')
    op.drop_index(op.f('ix_scheme_eligibility_results_scheme_id'), table_name='scheme_eligibility_results')
    op.drop_index(op.f('ix_scheme_eligibility_results_created_at'), table_name='scheme_eligibility_results')
    op.drop_index(op.f('ix_scheme_eligibility_results_citizen_id'), table_name='scheme_eligibility_results')
    op.drop_index('ix_eligibility_citizen_scheme', table_name='scheme_eligibility_results')
    op.drop_table('scheme_eligibility_results')
    op.drop_index(op.f('ix_profile_attributes_created_at'), table_name='profile_attributes')
    op.drop_index('ix_profile_attributes_citizen_name', table_name='profile_attributes')
    op.drop_index(op.f('ix_profile_attributes_citizen_id'), table_name='profile_attributes')
    op.drop_table('profile_attributes')
    op.drop_index(op.f('ix_digilocker_sessions_created_at'), table_name='digilocker_sessions')
    op.drop_index(op.f('ix_digilocker_sessions_citizen_id'), table_name='digilocker_sessions')
    op.drop_table('digilocker_sessions')
    # ### end Alembic commands ###
